### ISSUE TITLE
Writeback from github issue to Assembla

### ISSUE THREAD

**Issue by siemvaessen** [markfinger/assembla#25]
Hi there,

Can't figure this out from the current documentation, but it is possible to CRUD from Github back to Assembla, so:
# ticket99example in Assembla writes to Github. That tickets gets modified on Github, would that modification than be sent back to Assembla in #ticket99example

Thanks, Siem

**Comment by markfinger** [comment]
Hi,

I'm not too familiar with Github's webhooks, but I believe you could achieve something along those lines. I don't think it'll be trivial however.

For github -> assembla, You'll probably need an intermediary service which github's webhook can hit. The intermediary service would need to translate the webhook's request and pass it to assembla's API.

As for assembla -> github, I'm not entirely sure to be honest. They _may_ support webhooks, but if not, you'll need to poll the API, which - given the API request limits - will probably introduce a discernible lag in the data being replicated to github.

To be honest, I don't use Assembla anymore, so I'm not too familiar with what functionality they offer. It might be best to contact them directly.

Best of luck.

Cheers,
Mark

**Comment by siemvaessen** [comment]
Hi Mark,

Thanks for the feedback. Will look into this.

I am interested to learn why you left Assembla for Github. My main issue I do not have an out of the box overview list of projects from Github.

Thanks, Siem

**Comment by markfinger** [comment]
We're in the process of switching from assembla to github and an as-yet-undecided ticket tracker.

Assembla's source control works well but we wanted to consolidate everything, rather than the former state where we had repos scattered between bitbucket, assembla and github.

The ticket tracking part of assembla is something that we're still trying to find a solid replacement for ... one day, I hope.
