### ISSUE TITLE
Extremely slow response with large ticket sets

### ISSUE THREAD

**Issue by cgaskins-dl** [markfinger/assembla#26]
I believe I am having a problem similar to problem #13 - however my results slightly different instead of "hanging" the response is just extremely slow.  We have over 5000 tickets in our Assembla space and I get response time of almost 45 to 50 seconds when trying to find a specific ticket.

```
     for ticket in myspace.tickets(number=ticket_num):
```

I do have the latest release of the library.   Any suggestions for speeding this up?  Is there a faster way to lookup a specific ticket?

Thanks.

**Comment by markfinger** [comment]
I think this line is probably the cause: https://github.com/markfinger/assembla/blob/master/assembla/api.py#L320

The `tickets` function pulls in every ticket in a space, **then** filters them to match the kwargs.

It's been a long time since I've used this codebase, but you could probably just interact with the API directly to target a particular ticket's endpoint, eg: http://api-doc.assembla.com/content/ref/tickets_show.html

```
from assembla.api import Ticket

# ...

myspace.api._get_json(
    Ticket, 
    space=myspace, 
    rel_path=self._build_rel_path('tickets/%s' % ticket_num)
)
```

I haven't tested it, but **in principle** that should return a Ticket instance matching the number

**Comment by markfinger** [comment]
Actually, the `_get_json` would be something similar to

```
myspace.api._get_json(
    Ticket, 
    space=myspace, 
    rel_path=myspace._build_rel_path('tickets/%s' % ticket_num)
)
```
